project_id = "qjkaoghqatkminsufqfn"

[functions.create-panel]
verify_jwt = false

[functions.delete-panel]
verify_jwt = false

[functions.check-server-status]
verify_jwt = false

[functions.public-server-status]
verify_jwt = false
